spring.application.name=mastersys

spring.datasource.url=jdbc:postgresql://localhost:5432/academia
spring.datasource.username=postgres
spring.datasource.password=manager

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

#gerenciar e versionar script sql estar sempre na mesma versao que a aplicação

spring.flyway.enable=true
spring.flyway.locations=classpath:db/migration