services:
  postgres-db:
    image: postgres:15-alpine
    container_name: e-commerce-db
    environment:
      POSTGRES_DB: e_commerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: