CREATE TABLE cliente
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome  VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    cpf   VARCHAR(14)  NOT NULL UNIQUE
);

CREATE TABLE produto
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome       VARCHAR(100)   NOT NULL,
    preco      DECIMAL(10, 2) NOT NULL,
    quantidade_estoque INT            NOT NULL,
    ativo      BOOLEAN        NOT NULL DEFAULT TRUE
);

CREATE TABLE pedido
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id   BIGINT      NOT NULL,
    data_criacao TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status       VARCHAR(20) NOT NULL DEFAULT 'ABERTO',

    CONSTRAINT fk_pedido_cliente FOREIGN KEY (cliente_id) REFERENCES cliente (id)
);

CREATE TABLE item_pedido
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id      BIGINT         NOT NULL,
    produto_id     BIGINT         NOT NULL,
    quantidade     INT            NOT NULL,
    preco_unitario DECIMAL(10, 2) NOT NULL,

    CONSTRAINT fk_item_pedido_pedido FOREIGN KEY (pedido_id) REFERENCES pedido (id),
    CONSTRAINT fK_item_pedido_produto FOREIGN KEY (produto_id) REFERENCES produto (id)
);